name: Prod Workflow

on:
  push:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Restart Application on Server
        uses: appleboy/ssh-action@v1.0.0

        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: cd /home/admsrv/admin && ./restart.sh
  
